# config/services.yaml

parameters:
    # Placez ici les paramètres globaux

services:
    # Configuration par défaut pour les services définis dans ce fichier
    _defaults:
        autowire: true      # Injecte automatiquement les dépendances dans vos services
        autoconfigure: true # Enregistre automatiquement vos services comme commandes, abonnés aux événements, etc.

    # Définit les services pour le répertoire src/
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Autres définitions de services peuvent aller ici si nécessaire
    # Exemple: 
    # App\Service\SomeService:
    #     arguments:
    #         $someDependency: '@some_service'
